spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 47.95.117.206
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
server:
  port: 8667


tengxun:
  mpKey: 7Y5BZ-7DTC3-FVN3J-3Z4X2-ROLLJ-N6B7Q
